apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: ubuntu
spec:
  containers:
    - image: cloudgenius/toolimage:ubuntu
      command:
        - "sleep"
        - "604800"
      securityContext:
        privileged: true
      imagePullPolicy: IfNotPresent
      name: test
  restartPolicy: Always
