apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpressfiles
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: cg-storageclass
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/wordpressfiles"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpressfiles
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cg-storageclass
  resources:
    requests:
      storage: 20Gi
